NOPAINNOGAIN/Controllers/AparelhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NOPAINNOGAIN.Data;
using NOPAINNOGAIN.Models;

namespace NOPAINNOGAIN.Controllers
{
    [Authorize]
    public class AparelhoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AparelhoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Aparelho
        public async Task<IActionResult> Index()
        {
            return View(await _context.AparelhosGR.ToListAsync());
        }

        // GET: Aparelho/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aparelho = await _context.AparelhosGR
                .FirstOrDefaultAsync(m => m.ID == id);
            if (aparelho == null)
            {
                return NotFound();
            }

            return View(aparelho);
        }

        // GET: Aparelho/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aparelho/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Aparelho aparelho)
        {
            if (ModelState.IsValid)
            {
                aparelho.ID = Guid.NewGuid();
                _context.Add(aparelho);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aparelho);
        }

        // GET: Aparelho/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aparelho = await _context.AparelhosGR.FindAsync(id);
            if (aparelho == null)
            {
                return NotFound();
            }
            return View(aparelho);
        }

        // POST: Aparelho/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Aparelho aparelho)
        {
            if (id != aparelho.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aparelho);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AparelhoExists(aparelho.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aparelho);
        }

        // GET: Aparelho/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aparelho = await _context.AparelhosGR
                .FirstOrDefaultAsync(m => m.ID == id);
            if (aparelho == null)
            {
                return NotFound();
            }

            return View(aparelho);
        }

        // POST: Aparelho/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var aparelho = await _context.AparelhosGR.FindAsync(id);
            _context.AparelhosGR.Remove(aparelho);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AparelhoExists(Guid id)
        {
            return _context.AparelhosGR.Any(e => e.ID == id);
        }
    }
}

NOPAINNOGAIN/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NOPAINNOGAIN.Business.Interfaces;
using NOPAINNOGAIN.Data;
using NOPAINNOGAIN.Interfaces;
using NOPAINNOGAIN.Models;
using static System.Net.Mime.MediaTypeNames;

namespace NOPAINNOGAIN.Controllers
{
    [Authorize]
    public class FuncionariosController : Controller
    {

        private readonly IFuncionarioRepository _funcionarioRepository;
        private readonly IEnderecoRepository _enderecoRepository;
        private readonly ApplicationDbContext _context;

        public FuncionariosController(IFuncionarioRepository funcionarioRepository, IEnderecoRepository enderecoRepository, ApplicationDbContext context)
        {
            _funcionarioRepository = funcionarioRepository;
            _enderecoRepository = enderecoRepository;
            _context = context;
        }   
        [Route("dashboard")]
        public async Task<IActionResult> Index()
        {
            ViewBag.cliques = _context.MedGrupoGR.Count();
            ViewBag.comentarios = _context.ComentariosGR.Count();
            ViewBag.usuarios = _context.UsuariosGR.Count();
            ViewBag.resultado = _context.FuncionariosGR.Count();
            ViewBag.equipamentos = _context.AparelhosGR.Count();

            return View();
            
        }
        // GET: Funcionarios
        public async Task<IActionResult> Index2()
        {
            return View(await _funcionarioRepository.ObterTodos());
        }
        public async Task<IActionResult> Logar(Usuario usuario)
        {
            //SendMail();

            usuario.ID = Guid.NewGuid();
            _context.Add(usuario);
            _context.SaveChanges();
            return Redirect("/dashboard");
        }

        //public bool SendMail()
        //{
        //    try
        //    {
        //        // Estancia da Classe de Mensagem
        //        MailMessage _mailMessage = new MailMessage();
        //        // Remetente
        //        _mailMessage.From = new MailAddress("gramos@provertec.com.br");

        //        //Contrói o MailMessage
        //        _mailMessage.To.Add("gramos@provertec.com.br");
        //        _mailMessage.Subject = "Usuário Acabou de Logar no Sistema";
        //        _mailMessage.IsBodyHtml = true;
        //        _mailMessage.Body = $"<h4>Olá, tudo bem?</h4><br>Um usuário acabou de logar no Sistema, seu negócio está crescendo<h4>Orgulhe-se</h4>Obs: Iremos te trazer mais informações sobre os próximos passos do usuário no sistema<br><h4>Obrigado!</h4>";

        //        //CONFIGURAÇÃO COM PORTA
        //        SmtpClient _smtpClient = new SmtpClient("smtp.office365.com", Convert.ToInt32("587"));

        //        //CONFIGURAÇÃO SEM PORTA
        //        // SmtpClient _smtpClient = new SmtpClient(UtilRsource.ConfigSmtp);

        //        // Credencial para envio por SMTP Seguro (Quando o servidor exige autenticação)
        //        _smtpClient.UseDefaultCredentials = false;
        //        _smtpClient.Credentials = new NetworkCredential("gramos@provertec.com.br", "Flamengo@!22");

        //        _smtpClient.EnableSsl = true;

        //        _smtpClient.Send(_mailMessage);

        //        return true;

        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //}
        //public bool SendMail2()
        //{
        //    try
        //    {
        //        // Estancia da Classe de Mensagem
        //        MailMessage _mailMessage = new MailMessage();
        //        // Remetente
        //        _mailMessage.From = new MailAddress("gramos@provertec.com.br");

        //        string nome = Request.Form["Nome"];
        //        string documento = Request.Form["Documento"];
        //        DateTime data = Convert.ToDateTime(Request.Form["DataNascimento"]);
        //        double salario = Convert.ToDouble(Request.Form["Salario"]);
        //        //Contrói o MailMessage
        //        _mailMessage.To.Add("gramos@provertec.com.br");
        //        _mailMessage.Subject = "Funcionário Cadastrado Com Sucesso ";
        //        _mailMessage.IsBodyHtml = true;
        //        _mailMessage.Body = $"<h4>Olá Diego, tudo bem?</h4><br>Tivemos mais um cadastro de Funcionário, segue algumas informações importantes do novo Funcionário:<br><br>Nome: {nome}<br>Documento: {documento}<br>Data de Nascimento: {data.ToString("dd/MM/yyyy")}<br>Salario: R$ {salario.ToString("F")}<br><br>Obs: Seguiremos te trazendo mais informações sobre os próximos passos do usuário no sistema<br><h4>Obrigado!</h4>";

        //        //CONFIGURAÇÃO COM PORTA
        //        SmtpClient _smtpClient = new SmtpClient("smtp.office365.com", Convert.ToInt32("587"));

        //        //CONFIGURAÇÃO SEM PORTA
        //        // SmtpClient _smtpClient = new SmtpClient(UtilRsource.ConfigSmtp);

        //        // Credencial para envio por SMTP Seguro (Quando o servidor exige autenticação)
        //        _smtpClient.UseDefaultCredentials = false;
        //        _smtpClient.Credentials = new NetworkCredential("gramos@provertec.com.br", "Flamengo@!22");

        //        _smtpClient.EnableSsl = true;

        //        _smtpClient.Send(_mailMessage);

        //        return true;

        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //}

        // GET: Funcionarios/Details/5
        public async Task<IActionResult> Details(Guid id)
        {

            var funcionario = await ObterFuncionarioEndereco(id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public IActionResult Create()
        {
            return View();

        }
        // POST: Funcionarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Funcionario funcionario)
        {
            //  if (!ModelState.IsValid) return View(funcionario);

            var imgPrefixo = Guid.NewGuid() + "_";
            if (!await UploadArquivo(funcionario.ImagemUpload, imgPrefixo))
            {
                return View(funcionario);
            }

            funcionario.Imagem = imgPrefixo + funcionario.ImagemUpload.FileName;
            await _funcionarioRepository.Adicinar(funcionario);


           //SendMail2();
            return RedirectToAction(nameof(Index2));
        }

        // GET: Funcionarios/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {


            var funcionario = await ObterFuncionarioEndereco(id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Funcionario funcionario)
        {
            if (id != funcionario.ID) return NotFound();
            var funcionarioatualizacao = await ObterFuncionarioEndereco(id);

            funcionario.Imagem = funcionarioatualizacao.Imagem;
            // var funcionario1 = await ObterFuncionarioEndereco(id);
            

            if(funcionario.ImagemUpload != null)
            {
                var imgPrefixo = Guid.NewGuid() + "_";
                if (!await UploadArquivo(funcionario.ImagemUpload, imgPrefixo))
                {
                    return View(funcionario);
                }

                funcionario.Imagem = imgPrefixo + funcionario.ImagemUpload.FileName;
            }



            await _funcionarioRepository.Atualizar(funcionario);

            return RedirectToAction(nameof(Index2));
            if (!ModelState.IsValid) return View(funcionario);

        }

        // GET: Funcionarios/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {

            var funcionario = await ObterFuncionarioEndereco(id);

            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var funcionario = await ObterFuncionarioEndereco(id);

            if (funcionario == null) return NotFound();

            await _funcionarioRepository.Remover(id);

            return RedirectToAction(nameof(Index2));
        }

        public async Task<IActionResult> ObterEndereco(Guid id)
        {
            var funcionario = await ObterFuncionarioEndereco(id);

            if (funcionario == null)
            {
                return NotFound();
            }

            return PartialView("_DetalhesEndereco", funcionario);
        }

        public async Task<IActionResult> AtualizarEndereco(Guid id)
        {
            var funcionario = await ObterFuncionarioEndereco(id);

            if (funcionario == null)
            {
                return NotFound();
            }

            return PartialView("_AtualizarEndereco", new Funcionario { Endereco = funcionario.Endereco });
        }

NOPAINNOGAIN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NovaAplicação</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Itim&family=Rubik+Wet+Paint&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a style="font-size: 25px" class="navbar-brand" asp-area="" asp-controller="Funcionarios" asp-action="Index"><img src="~/Imagem(Login)/logo 2.png" class="logo" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="funcionario">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item" id="funcionario">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedGrupoes" asp-action="Index">MedGrupo</a>
                        </li>*@
                        <li class="nav-item" id="funcionario">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aparelho" asp-action="Index">equipment registration</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <style>
        input,
        select,
        file,
        textarea {
            max-width: 300px;
        }
    </style>
</body>
</html>

NOPAINNOGAIN/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -  ProjetoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Itim&family=Rubik+Wet+Paint&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>